steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'config', 'set', 'project', 'project-id']
  
  
# This step Build the docker image
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Docker Build
  args:
  - 'build'
  - '-t'
#   - 'gcr.io/$PROJECT_ID/test-worker:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo:$COMMIT_SHA'
  - '.'
  
  
# This step pushes the image to Container Registry
# The PROJECT_ID and SHORT_SHA variables are automatically
# replaced by Cloud Build.
- name: 'gcr.io/cloud-builders/docker'
  id: Docker Push
  args:
  - 'push'
#   - 'gcr.io/$PROJECT_ID/test-worker:$COMMIT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo:$COMMIT_SHA'
  
  
