
#Setup GCP Project
steps:
- name: 'gcr.io/task-project-374915/custom-builder-images/'
#   args: ['gcloud', 'config', 'set', 'project', 'project-id']
  id: Determine IP of this build worker
  
  
# # This step Build the docker image
# # The PROJECT_ID and SHORT_SHA variables are automatically
# # replaced by Cloud Build.
# - name: 'gcr.io/cloud-builders/docker'
#   id: Docker Build
#   args:
#   - 'build'
#   - '-t'
#   - 'gcr.io/$PROJECT_ID/test-worker:$COMMIT_SHA'
#   - '.'
  
  
# # This step pushes the image to Container Registry
# # The PROJECT_ID and SHORT_SHA variables are automatically
# # replaced by Cloud Build.
# - name: 'gcr.io/cloud-builders/docker'
#   id: Docker Push
#   args:
#   - 'push'
#   - 'gcr.io/$PROJECT_ID/test-worker:$COMMIT_SHA'
